### PR TITLE
[Omega] dependency updates and OS build fixes

### PR DESCRIPTION
**Pull request by AlwinEsch**
Due to reported problems on Apple builds by ARM CPU I try to becomes it fixed. Firstly I look about all dependencies on newest version and then more in detail.

Also maybe are some patches no more needed or new ones necessary.

For now mainly as request to see on all OS the Jenkins build.

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]

**Comment by AlwinEsch** [comment]
Hi @phunkyfish, this is now a minimal update to become the OS fixed. The other request https://github.com/xbmc/inputstream.ffmpegdirect/pull/241 can be then comes later.

**Comment by phunkyfish** [comment]
Thanks @AlwinEsch !!!

**Comment by howie-f** [comment]
this breaks build with` autoreconf (GNU Autoconf) 2.69 Debian Bullseye repositories` while checking for autoreconf >= 2.53...

```
[ 12%] Performing patch step for 'libzvbi'
aclocal.m4:17: warning: this file was generated for autoconf 2.71.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
/home/fhw/.tmp/.kodi-build-binaddons/build/libzvbi/src/libzvbi/configure.ac:4: error: Autoconf version 2.71 or higher is required
/home/fhw/.tmp/.kodi-build-binaddons/build/libzvbi/src/libzvbi/configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
checking for automake >= 1.11.2...
  testing automake... found 1.16.3
checking for autoreconf >= 2.53...
  testing autoreconf... found 2.69
aclocal.m4:17: warning: this file was generated for autoconf 2.71.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
/home/fhw/.tmp/.kodi-build-binaddons/build/libzvbi/src/libzvbi/configure.ac:4: error: Autoconf version 2.71 or higher is required
/home/fhw/.tmp/.kodi-build-binaddons/build/libzvbi/src/libzvbi/configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
Processing /home/fhw/.tmp/.kodi-build-binaddons/build/libzvbi/src/libzvbi/configure.ac
aclocal.m4:17: warning: this file was generated for autoconf 2.71.
You have another version of autoconf.  It may work, but is not guaranteed to.
If you have problems, you may need to regenerate the build system entirely.
To do so, use the procedure documented by the package, typically 'autoreconf'.
configure.ac:4: error: Autoconf version 2.71 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
Running autoreconf...
autoreconf: Entering directory `.'
autoreconf: running: autopoint --force
autoreconf: running: aclocal --force --warnings=no-portability -I m4
configure.ac:4: error: Autoconf version 2.71 or higher is required
configure.ac:4: the top level
autom4te: /usr/bin/m4 failed with exit status: 63
aclocal: error: /usr/bin/autom4te failed with exit status: 63
autoreconf: aclocal failed with exit status: 63
make[6]: *** [CMakeFiles/libzvbi.dir/build.make:119: libzvbi-prefix/src/libzvbi-stamp/libzvbi-patch] Error 1
make[5]: *** [CMakeFiles/Makefile2:95: CMakeFiles/libzvbi.dir/all] Error 2
make[4]: *** [Makefile:149: all] Error 2
make[3]: *** [CMakeFiles/libzvbi.dir/build.make:141: build/libzvbi/src/libzvbi-stamp/libzvbi-build] Error 2
make[2]: *** [CMakeFiles/Makefile2:511: CMakeFiles/libzvbi.dir/all] Error 2
make[1]: *** [CMakeFiles/Makefile2:175: CMakeFiles/package-inputstream.ffmpegdirect.dir/rule] Error 2
make: *** [Makefile:150: package-inputstream.ffmpegdirect] Error 2
```

had to install `autoconf (2.71-3)` and `automake (1:1.16.5-1.3)` from bookworm repos to get it working.
not a big deal if you know it but can we do something about this?
guess there are people out there still using bullseye for a while. not necessarily including myself ;-)

**Comment by phunkyfish** [comment]
Maybe we can fix this as part of https://github.com/xbmc/inputstream.ffmpegdirect/pull/241

**Pull request merged**
