### PR TITLE
Added autoreconf step to libzvbi dependency: update autotools scripts…

### PR DESCRIPTION
**Pull request by paolo-sz**
… in order to support newer architectures, eg. aarch64 (#68)

### CODE REVIEW

**Comment by phunkyfish** [comment]
You probably need to add travis to install autopoint if it’s required.

Try adding it to the `.travis.yml` for Linux and osx. You’ll see that yasm is already installed. Add it there.

**Comment by paolo-sz** [comment]
Installing autopoint on osx is not that easy... sigh...
googled a little bit and I hope now travis will be happy...

**Comment by phunkyfish** [comment]
Nice, it looks good. And more importantly does it solve it for your platform.

**Comment by phunkyfish** [comment]
BTW the tvOS error is unrelated.

**Comment by paolo-sz** [comment]
> BTW the tvOS error is unrelated.

Yes, by looking at the log I was guessing so.

**Comment by phunkyfish** [comment]
I will hopefully merge this tomorrow.

**Comment by paolo-sz** [comment]
No rush.
In the meanwhile, and for other reasons, I switched to kodi android compilation (for the same HW) and there the issue is not showing up...

**Pull request merged**
