### PR TITLE
Update StreamManager.h

### PR DESCRIPTION
**Pull request by Johpin1**
During compilation of inputstream.ffmpegdirect-20.3.0-Nexus on Slackware aarch64 I got the error:

/home/john/Downloads/addons/inputstream.ffmpegdirect/src/StreamManager.h:60:16: error: �..virtual void InputStreamFFmpegDirect::SetVideoResolution(int, int)�.. marked �..override�.., but does not override 60 | virtual void SetVideoResolution(int width, int height) override;

=> Solved by removing "override" from line 60 in StreamManager.h

### CODE REVIEW

**Comment by phunkyfish** [comment]
I don’t understand why this change is required. The signature of the method is correct and matches the API.

**Comment by phunkyfish** [comment]
Here is the API signature:

```cpp
  //============================================================================
  /// @brief Notify current screen resolution
  ///
  /// @param[in] width Width to set
  /// @param[in] height Height to set
  ///
  virtual void SetVideoResolution(unsigned int width, unsigned int height) {}
  //----------------------------------------------------------------------------

  //============================================================================
  /// @brief Notify current screen resolution and max screen resolution allowed
  ///
  /// @param[in] width Width to set
  /// @param[in] height Height to set
  /// @param[in] maxWidth Max width allowed
  /// @param[in] maxHeight Max height allowed
  ///
  virtual void SetVideoResolution(unsigned int width,
                                  unsigned int height,
                                  unsigned int maxWidth,
                                  unsigned int maxHeight)
  {
  }
```

**Comment by phunkyfish** [comment]
The API is identical on both the Nexus and Omega branches.

So I'm not sure where the signature coming from your error is from, with `(int, int)`. That was however the signature from the Matrix branch, where there was a single method with this signature `virtual void SetVideoResolution(int width, int height) {}`

Is it possible you are compiling against wrong source for xbmc?

**Comment by Johpin1** [comment]
I have used:
inputstream.ffmpegdirect-20.3.0-Nexus.zip
xbmc-20.3-Nexus.zip
No Matrix.

**Comment by Johpin1** [comment]
As a test I have also tried for Omega: the error does not appear.

Also tested for Matrix => only two errors about missing \#include\<cstdint\> as mentioned in issue 288, but not the error mentioned in this PR.
inputstream.ffmpegdirect-19.3-Matrix.zip
xbmc-19.3-Matrix.zip

Build again for 20.3-Nexus, override error still appears.

**Comment by phunkyfish** [comment]
So why not just use Omega? It will be released in a couple of weeks anyway.

**Comment by Johpin1** [comment]
After adapting the code I could built the addon successfully for Nexus. It works.

There is no SlackBuild for Kodi Omega yet. I can do the build according the README from Kodi. The only reason for me could be to check the CEC adapter will be available. For Matrix and Nexus it is missing if you compile on Slackware arm despite of libcec is found during configuring.

**Comment by phunkyfish** [comment]
Ok, fair. Then I think it’s likely best to stick with the build you have for now. And then switch to Omega once it’s ready.

**Comment by Johpin1** [comment]
I decided to try Kodi Omega and build it successfully, also inputstream.ffmpegdirec, inputstream.rtmp and pvr.iptvsimple are fine, only inputstream.adaptive couldn't be compiled:

`[ 30%] Building CXX object CMakeFiles/inputstream.adaptive.dir/src/Session.cpp.o
/tmp/SBo/inputstream.adaptive-21rc2-Omega/src/Session.cpp: In member function ‘bool SESSION::CSession::ExtractStreamProtectionData(PLAYLIST::CPeriod::PSSHSet&, std::vector<unsigned char>&, std::string)’:
/tmp/SBo/inputstream.adaptive-21rc2-Omega/src/Session.cpp:1427:40: error: ‘class AP4_Movie’ has no member named ‘GetPsshAtoms’
 1427 |   AP4_Array<AP4_PsshAtom>& pssh{movie->GetPsshAtoms()};
      |                                        ^~~~~~~~~~~~
/tmp/SBo/inputstream.adaptive-21rc2-Omega/src/Session.cpp:1427:54: error: invalid initialization of non-const reference of type ‘AP4_Array<AP4_PsshAtom>&’ from an rvalue of type ‘<brace-enclosed initializer list>’
 1427 |   AP4_Array<AP4_PsshAtom>& pssh{movie->GetPsshAtoms()};
      |                                                      ^
make[2]: *** [CMakeFiles/inputstream.adaptive.dir/build.make:118: CMakeFiles/inputstream.adaptive.dir/src/Session.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:385: CMakeFiles/inputstream.adaptive.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
`
Do you have any idea?

I will close this PR, because the override error is not valid for Kodi Omega.

**Comment by phunkyfish** [comment]
Please create an issue on the inputstream.adaptive GitHub for this. They should be able to help. You can also mention me on the issue so I can follow progress.

**Comment by marvin2k1** [comment]
same problem here:
In file included from /home/kodi/kodirelease/Omega/xbmc-Omega/kodi-build/inputstream.ffmpegdirect/src/stream/DemuxStream.h:26,
                 from /home/kodi/kodirelease/Omega/xbmc-Omega/kodi-build/inputstream.ffmpegdirect/src/stream/FFmpegStream.h:13,
                 from /home/kodi/kodirelease/Omega/xbmc-Omega/kodi-build/inputstream.ffmpegdirect/src/stream/FFmpegStream.cpp:8:
/usr/include/x86_64-linux-gnu/libavformat/avformat.h:2107:71: note:   initializing argument 3 of ‘uint8_t* av_stream_get_side_data(const AVStream*, AVPacketSideDataType, int*)’
 2107 |                                  enum AVPacketSideDataType type, int *size);
      |                                                                  ~~~~~^~~~
make[2]: *** [CMakeFiles/inputstream.ffmpegdirect.dir/build.make:132: CMakeFiles/inputstream.ffmpegdirect.dir/src/stream/FFmpegStream.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:110: CMakeFiles/inputstream.ffmpegdirect.dir/all] Error 2
make: *** [Makefile:156: all] Error 2
kodi@kodi-xubuntu:~/kodirelease/Omega/xb

**Comment by phunkyfish** [comment]
What makes you think this is the same problem?

It looks to me like a mismatch in ffmpeg versions. And you really shouldn’t post on closed issues.

**Comment by marvin2k1** [comment]
Sorry, i was no able to install ffmpeg on xubuntu 22 omega, since the end of ppa for linux users, the way to update has been to much hard. I be able to instal iptv and it works but cant open sources since fffmpeg give us that error. Finally i found more problems on sudo make process, now, im not very sure if it some from kodi-build. Unfortunatelly are not information for uses how to manage updates from source.

**Comment by phunkyfish** [comment]
The issue is likely they you have ffmpeg 7 on your Linux install and kodi Omega only has ffmpeg 6.

you will likely need to build for Kodi 22 which uses ffmpeg 7. However ffmpegdirect is still on ffmpeg 6. Here is the PR to follow for when that is ready: https://github.com/xbmc/inputstream.ffmpegdirect/pull/304

**Comment by basilgello** [comment]
@marvin2k1 if you are compiling stuff for Debian derivatives (Ubuntu, Mint, Kali etc), you can rebuild any package from Debian sid using Docker for your target distro.

**Pull request closed without merging**
