### PR TITLE
changelog and version - v1.18.3 - release bump

### PR DESCRIPTION
**Pull request by phunkyfish**
v1.18.3
- Update: Release bump

### CODE REVIEW

**Comment by phunkyfish** [comment]
@Gregsr if you can check this on Android 32bit once it has built. I reckon the crash you have is somehow related to Android SDK change/ffmpeg build.

Once built the testbuilds will be here (it can take a while): https://jenkins.kodi.tv/blue/organizations/jenkins/xbmc%2Finputstream.ffmpegdirect/detail/PR-82/1/artifacts

**Comment by Gregsr** [comment]
Kodi crashes

**Comment by phunkyfish** [comment]
> Kodi crashes

With 1.18.3?

**Comment by Gregsr** [comment]
> > Kodi crashes
> 
> With 1.18.3?

Yes

**Pull request closed without merging**
