### PR TITLE
Lean mode

### PR DESCRIPTION
**Pull request by phunkyfish**
v1.15.0
- Added: Add fast open for manifest stream and test setting for realtime off
- Fixed: Honour realtime stream property
- Fixed: Fix using prev button to seek back to start of stream
- Fixed: Ensure no slash at end of timeshift buffer path
- Fixed: Make sure write segment file is closed when buffer is destroyed
- Fixed: Use overwrite when opening files for write for compatibility with SMB on Android
- Fixed: Don't start timeshift and exit if index file cannot be created
- Update: If any timeshift file cannot be created log free disk space
- Fixed: Avoid crash for zero byte or partial timeshift segment files
- Fixed: Only read ffmpeg logging setting on stream start
- Update: Redact username and password for urls in log statements
- Fixed: Only create timeshift directory if it does not exist

### CODE REVIEW

**Comment by phunkyfish** [comment]
@vpeter4 

Can you test this PR without overriding the `is_realtime_stream` property in your M3U?

The new advanced options should let you try both cases you raised. If both work as expected I'll clean it up.

**Comment by vpeter4** [comment]
I will test this PR but I'm not sure if is correct. If you look here how it was done before
https://github.com/xbmc/xbmc/pull/16355/files#diff-4b73a3a0982479ec64d6aba7b0f64380L262
you see that one call `avformat_open_input()` was always made. Now when using `useFastOpenForManifestStreams = false` it is not called even once. But maybe this is ok too. Will let you know.

**Comment by vpeter4** [comment]
I just tested and it works for both cases.
The only thing is typo here https://github.com/xbmc/inputstream.ffmpegdirect/pull/59/commits/48a70f38232ac93cdb83732f25650b22ffdf3f48#diff-b856318a1bf69d39ab8e85ca93add622R904
**useFastOpenForManifestStreams** is boolean variable and it must be like
`if (kodi::GetSettingBoolean("useFastOpenForManifestStreams"))`

I see this option is default _true_ which means it doesn't change anything from current operation. But if set to _false_ it doesn't opens stream twice which helps in my case.

**Comment by phunkyfish** [comment]
Ah, yes, you’re right. It should != true.

**Comment by vpeter4** [comment]
I was also little confused: name includes fast but must be set false to get in effect :)

**Comment by phunkyfish** [comment]
Should be fixed in latest push. The extra setting for realtime off is only applied to catchup streams.

**Comment by vpeter4** [comment]
All good now.

**Pull request merged**
