### PR TITLE
Continued playback of catchtup streams which don't support delayed live streams

### PR DESCRIPTION
**Pull request by phunkyfish**
v1.10.0
- Added: Continued playback of catchtup streams which don't support delayed live streams
- Added: Skip unsupported seeks like ones too close to live or those less one minute for streams that only allow a 1 minute granulaity
- Added: Limit seeking for terminating 1 second streams to within 1 minute of live and for 60 streams 2 minutes
- Update: Debian control file
- Update: gas-preprocessor to latest version and remove patch that is no longer required
- Update: .gitignore
- Fixed: Fix arch typo ffmpeg darwin_embedded
- Fixed: Cleanup apple frameworks usage in cmakelists
- Added: Change logging implementation and deprecate use of NOTICE level
- Added: Allow streams to be opened using cURL in addition to FFmpeg
- Update: Fix TS Streams by disallowing streaminfo for realtime streams
- Update: MKV Attachment and IsTransportStreamReady() updates from kodi

### CODE REVIEW

**Comment by phunkyfish** [comment]
@Mr-Groch you can try this, you'll need a recent kodi and 4.13.0 of iptvsimple.

It will only work for a seek of at least 3 mins, and was only tested on a stream with 1 minute granularity. It's a basic version to start with. Only seeking back 3 mins it will repeat play for 20 mins or so before the offset catches up with it and it EOF's.

**Comment by Mr-Groch** [comment]
I have just made few quick tests with XC stream. Overall I'm really positively surprised - I have not expected so smooth catchup stream "restart". No buffering, just some artifacts visible for half a second. But what I think I have observed - for each "restart", playback will jump aboout 1 second backward. So after 30 minutes of watching, when I have timeshifted 5 minutes first, after last "restart" it played again about 5 seconds.

I have run 3 test cases:

1. Tried to timeshift 3 minutes back from live - it played 3 minutes, after that catchup stream "restarted" fine and played fine next 3 minutes. After that (next 3 minutes) it stopped. Tried 2 times on different channels - always after next 3 minutes (6 minutes overall) it will stop.
2. In my second test case I have timeshift back 5 minutes. This time I was able to watch about 30 minutes fine. After that I have stopped manually.
3. Tried to timeshift 1 minute back - this time I've noticed a regression - it will not work - after so short timeshift, it will play again and again same 1-2 second frgament in loop... Tried few times on different channels.

**Comment by phunkyfish** [comment]
Yes, ignore the 1 minute timeshift. That will definitely not work.

For the 3 mins and 5 mins test the 5 mins last roughly twice as many rounds as the 3 mins. Which is roughly correct.

So there must be an offset which is aggregating somewhere but at least it’s consistent!

**Comment by phunkyfish** [comment]
The real solution to this will be detecting the EOF in the deumxer before it goes to the VideoPlayer.

If I can figure that out then it will work for this but would also allow http reconnect similar to VLC. Now that would be cool.

**Comment by phunkyfish** [comment]
@Mr-Groch, latest version should be more stable and support a one minute seek with a one minute granularity.

Can you test it and see what you think? I didn't a chance to test the 1 second granularity feed yet so you might try that too.

**Comment by phunkyfish** [comment]
Ok, so it appears to work on the 1 second stream but only if the seek is 1 min or later. I’ll see if I can get 30 seconds working tomorrow.

10 seconds and less will always just play the live stream anyway regardless of granularity.

**Comment by phunkyfish** [comment]
@Mr-Groch 

Ok, should be working now.

Notes:

- For one minute streams if you live seek for < 60 seconds it has no effect. One caveat issue is that if you are live at the start of a programme you can't seek back until after 1 minute. This is unavoidable.
- For one second streams it won't allow < 10 seconds from live as that's the threshold for live playback. Same caveat.
- For the one second stream it actually gives you more than 30 seconds each time you seek from live so it will converge on live eventually. It may just be this stream that does this. 60 seconds will continue forever.
- Found a bug in kodi where it can skip programmes using the prev button, next is ok so ther eis a workaround. It's not the addon.

Last point is that you'll need to be the judge of how well the continuing work on both the 1 minute and 1 second streams, it's very heard to tell when you don't speak the language. Also, this implementation is different to the last one. It's now baed on EOF's and far more reliable but you do reuire an EOF to occur for it to work. I don't know if all stream work like this but the test streams do.

**Comment by phunkyfish** [comment]
Fix for PVR bug where using the prev button can can skip programmes: https://github.com/xbmc/xbmc/pull/17757

EDIT: Kodi PR merged.

**Comment by Mr-Groch** [comment]
So far I have tested with `XC` catchup type in **TS** and **HLS** formats.

**TS** generally works better - transitions are almost seamlessly. I have timeshifted 1, 3 and 10 minutes few times on different channels and watched till 2-3 "restarts". Only once I've observed problem with really big jumps (about 10 seconds forward) each minute, but I can not reproduce that once more... It may be linked with seeking backwards 3 minutes first and then forwards 2x times 1 minute.

**HLS** stream "restarts" are not so seamless when timeshited 3 minutes - I can see little jump each "restart" (stream will jump about 2-3 seconds). But I can live with that - I'm aware that this can be problem with segmented video in HLS stream and we can't do nothing about it... (or we can?). But 1 minute timeshifting is broken with **HLS** `XC` catchup - it will loop same 1 minute fragment after "restart", but not infinitously - first 1 minute will loop, next it will jump 1 minute forward, next "restart" another loop, then another 1 minute jump forward and so on...

Another problem I have observed is regression in https://github.com/kodi-pvr/pvr.iptvsimple/issues/329 - resume from pause from live issue is back for **HLS** stream will jump to live (for **TS** stream - it will stop playing and exit to guide). I have tested pausing first more than 1 minute and next more than 3 minutes - same behaviour.

**Comment by phunkyfish** [comment]
> So far I have tested with `XC` catchup type in **TS** and **HLS** formats.
> 
> **TS** generally works better - transitions are almost seamlessly. I have timeshifted 1, 3 and 10 minutes few times on different channels and watched till 2-3 "restarts". Only once I've observed problem with really big jumps (about 10 seconds forward) each minute, but I can not reproduce that once more... It may be linked with seeking backwards 3 minutes first and then forwards 2x times 1 minute.
> 
> **HLS** stream "restarts" are not so seamless when timeshited 3 minutes - I can see little jump each "restart" (stream will jump about 2-3 seconds). But I can live with that - I'm aware that this can be problem with segmented video in HLS stream and we can't do nothing about it... (or we can?). But 1 minute timeshifting is broken with **HLS** `XC` catchup - it will loop same 1 minute fragment after "restart", but not infinitously - first 1 minute will loop, next it will jump 1 minute forward, next "restart" another loop, then another 1 minute jump forward and so on...
> 

Firstly, we are bound by the limits of HLS here, remember we can only seek to a time and then play what the server gives us, we can't tell if it's right or wrong. So I think we need to live with this.

On the second point I have not been able to repro this but as the stream is not in my language it is hard to tell if this is happening as it would just look like a cut scene to me. It is possible we are always off by 60 seconds though but I'm not sure if that means we should not support seek < 3 minutes or if 1 min seeks should be ok but the logic is wrong. If you can figure out what's going on exactly I can try and progress it.

> Another problem I have observed is regression in [kodi-pvr/pvr.iptvsimple#329](https://github.com/kodi-pvr/pvr.iptvsimple/issues/329) - resume from pause from live issue is back for **HLS** stream will jump to live (for **TS** stream - it will stop playing and exit to guide). I have tested pausing first more than 1 minute and next more than 3 minutes - same behaviour.

Ok, this is fixable. The new logic can effect this feature and I didn't think to check it.

**Comment by phunkyfish** [comment]
Ok, here is how it works now:

- For catchup streams that terminate there is a minimum distance from live a stream can seek to/from. For streams with a 1 second granularity it's 1 minute, and for stream with a 60 second granularity it's 2 minutes. The reason for this window on terminating streams is to allow the restart functionality to work.
- For all catchup streams any seek to within 10 seconds of live would be considered live and will switch to the default URL. For this reason seeking from live to less than 10 seconds has no effect.

**Comment by Mr-Groch** [comment]
I've checked `XC` catchup (**TS** and **HLS**) and there is regression compared to yesterday... Minimum distance from live seems to work OK. But stream is always stopping after 2 minutes after "restart". For example - I've timeshifted 3 minutes, after about 3 minutes "restart" happens and it is playing OK but after next 2 minutes it will stop playing and go back to guide...

**Comment by phunkyfish** [comment]
Sorry, fixed now. Forget to check for stream restart in latest commit.

**Comment by Mr-Groch** [comment]
Its going better and better, but not ideal yet ;)

Playback is continuous for `XC` and `shift` catchup types when timeshifted 3 minutes and 1 minute respectively and watched over 10 minutes. Resuming from pause works. But I have observed 2 issues:

1. When watching from catchup (timeshifted) for both `XC` and `shift` and tried to go to live by seek forward or by pressing "skip next" button it will stick to about -51-59 secs from live (at least KODI UI is showing that timeshift, maybe stream is live - I don't have possibility to check if this is live or really 1 minute before live)
2. Sometimes it is not possible to seek 1 minute back from live for `shift` catchup type. I'm trying to seek 1 minute but KODI will show for example -59 s and then it will jump back to live. For `XC` this problem does not occur - when I try to timeshift 3 minutes it will always jump 3:01 to 3:05 and timeshift will be OK.

**Comment by phunkyfish** [comment]
> Its going better and better, but not ideal yet ;)
> 
> Playback is continuous for `XC` and `shift` catchup types when timeshifted 3 minutes and 1 minute respectively and watched over 10 minutes. Resuming from pause works. But I have observed 2 issues:
> 
> 1. When watching from catchup (timeshifted) for both `XC` and `shift` and tried to go to live by seek forward or by pressing "skip next" button it will stick to about -51-59 secs from live (at least KODI UI is showing that timeshift, maybe stream is live - I don't have possibility to check if this is live or really 1 minute before live)

Just check the log live as you are watching the stream. There will be a `Seek to live` or `Seek to catchup` depending on which seek type it is. Also if it restarts the steam there will be log statement like `EOF detected on terminiating catchup stream, starting continuing stream at offset: ...`. 

The timeshift clock is not our control. I have found that sometimes it's off even though we are back live. Not sure why this happens.

> 2. Sometimes it is not possible to seek 1 minute back from live for `shift` catchup type. I'm trying to seek 1 minute but KODI will show for example -59 s and then it will jump back to live. For `XC` this problem does not occur - when I try to timeshift 3 minutes it will always jump 3:01 to 3:05 and timeshift will be OK.

Ok, I will need an example stream for this. Should be easy enough to fix once I can reproduce.

Also, a log snippet of this one occurring would be useful.

**Comment by Mr-Groch** [comment]
Ad 1. Maliciously stream - failed to repeat now... Morning almost always this was happening, but now I tried many times with `XC` and `shift` lists and always when back to live, KODI progress was also showing live...

Ad 2. This happens sometimes, I haven't found no reasonable repro pattern. I tried 5 times to make it happen. If we are using 1 second granularity it can be easily fixed by allowing timeshift minimum not 60 seconds from live, but 50 seconds :) Here is log snippet:

```
2020-04-29 16:27:33.753 T:13498    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekCatchupStream - Seek offset: 86360 - time: 2020-04-29.16:26:33
2020-04-29 16:27:33.753 T:13498    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekDistanceSupported - seekDistanceSecs (skipping): 53, actual: 63
```

**Comment by phunkyfish** [comment]
> Ad 1. Maliciously stream - failed to repeat now... Morning almost always this was happening, but now I tried many times with `XC` and `shift` lists and always when back to live, KODI progress was also showing live...
> 

Ok, well if you do see it again just check the log but I reckon it's playing live and the timeshift clock is just off slightly and not much we can do about it.

> Ad 2. This happens sometimes, I haven't found no reasonable repro pattern. I tried 5 times to make it happen. If we are using 1 second granularity it can be easily fixed by allowing timeshift minimum not 60 seconds from live, but 50 seconds :) Here is log snippet:
> 
> ```
> 2020-04-29 16:27:33.753 T:13498    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekCatchupStream - Seek offset: 86360 - time: 2020-04-29.16:26:33
> 2020-04-29 16:27:33.753 T:13498    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekDistanceSupported - seekDistanceSecs (skipping): 53, actual: 63
> ```

We use 0.9f * 60 for this already ;)

Changed to 0.8f * 60. Let me know if it works as you expect now.

**Comment by Mr-Groch** [comment]
Maybe there is another place in code with those limit boundaries, because it does not fix it. There is no "(skipping)" in log when KODI says -55secs instead of -1 minute:

```
2020-04-29 18:55:39.490 T:27280    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekCatchupStream - Seek offset: 86388 - time: 2020-04-29.18:54:45
2020-04-29 18:55:39.490 T:27280    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekDistanceSupported - seekDistanceSecs: 55, actual: 65
```

But stream will go back to live (KODI progress also), not catchup...

**Comment by phunkyfish** [comment]
If there is no `(skipping)` in the log statement then that means the seek should be valid and should have occurred.

Oh, lightbulb moment.

**Comment by phunkyfish** [comment]
Ok, new implementation for the seek distances. Fingers crossed this is right now.

It will require some rigorous testing.

**Comment by Mr-Groch** [comment]
I've tested today morning this PR and it was looking OK. It was quick test with `shift` **HLS** and `XC` **TS** streams. I want to test thoroughly now, but i've noticed new commits 2 hours ago, so I've updated. Unfortunately timeshifting is now broken (checked `XC` **TLS**) - I tried to seek from live 3 minutes, 10 minutes, even 50 minutes  and more, but It was stuck to live (KODI UI progress times was showing timeshifted time):

```
2020-05-03 23:55:25.042 T:23096    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekCatchupStream - Seek offset: 82207 - time: 2020-05-03.22:45:18
2020-05-03 23:55:25.042 T:23096    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekDistanceSupported - seek distance of 1808 seconds is ok
2020-05-03 23:55:25.042 T:23096    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: TargetDistanceFromLiveSupported - 4207 seconds from live is ok
2020-05-03 23:55:25.042 T:23096    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: SeekCatchupStream - Seek to catchup
2020-05-03 23:55:25.043 T:23096    INFO <general>: AddOnLog: Inputstream FFmpeg Direct: OpenWithCURL - IO handled by Kodi's cURL
2020-05-03 23:55:25.044 T:23096   ERROR <general>: AddOnLog: Inputstream FFmpeg Direct: ffmpeg[(nil)X]: [mpegts] Unable to seek back to the start
```

**Comment by phunkyfish** [comment]
Hmm, ok. Let me remove the curl file stuff in the morning. It must be getting in the way. I can keep that for a later PR and get it working properly.

**Comment by phunkyfish** [comment]
Ok, I have disabled the new curl stuff. It should now behave as it did previously.

**Comment by Mr-Groch** [comment]
It is working fine now

**Comment by phunkyfish** [comment]
Clearly the cURL feature needs a bit of work 😉

EDIT: actually I think I know where the issue is.

**Comment by phunkyfish** [comment]
@Mr-Groch 

I have fixed the cURL feature so that will now be the default for TS based stream. Let me know if it is any different with this issue: https://github.com/kodi-pvr/pvr.iptvsimple/issues/330

It would be good to check if cURL acts differently to FFmpeg.

**Comment by Mr-Groch** [comment]
I've checked `XC` **TS** - works great. But why TS only? Stream from issue https://github.com/kodi-pvr/pvr.iptvsimple/issues/330 was HLS and I won't have it until next week...

**Comment by phunkyfish** [comment]
> I've checked `XC` **TS** - works great. But why TS only? Stream from issue [kodi-pvr/pvr.iptvsimple#330](https://github.com/kodi-pvr/pvr.iptvsimple/issues/330) was HLS and I won't have it until next week...

I don’t think cURL can open HLS it needs to be handled directly by ffmpeg.

But if the redirects issue doesn’t occur using cURL then it means we probably just need to get the effective url. It would be great if we could test whether or not this is needed as it may incur an overhead.

But once you are happy with this PR let’s put it in and we can tackle the redirect stuff separately. Maybe. Test when detecting the stream type can check for any redirects.

**Comment by phunkyfish** [comment]
Ok, I've cleanup up the last few commits. I'll merge this tomorrow.

**Pull request merged**
