### PR TITLE
[Omega] Increase version (API related)

### PR DESCRIPTION
**Pull request by CastagnaIT**
Related to:
https://github.com/xbmc/xbmc/pull/23540
https://github.com/xbmc/xbmc/pull/23541

### CODE REVIEW

**Comment by phunkyfish** [comment]
Failing on Apple platforms. Kicked off a rebuild.

**Comment by CastagnaIT** [comment]
i dont know apple systems but seem something wrong with `libzvbi` on _osx-arm64_ build:
```
configure: error: in `/Users/Shared/jenkins/workspace/binary-addons/kodi-osx-arm64-Omega/tools/depends/target/binary-addons/macosx13.1_arm64-target-release/build/libzvbi/src/libzvbi-build/libzvbi-prefix/src/libzvbi-build':
configure: error: C compiler cannot create executables
See `config.log' for more details
Making all in xzdec
Making install in libxml
2
checking size of unsigned...  /Users/Shared/jenkins/workspace/binary-addons/kodi-osx-arm64-Omega/tools/depends/target/binary-addons/macosx13.1_arm64-target-release/build/libxml2/src/libxml2/install-sh -c -d '/Users/Shared/jenkins/workspace/binary-addons/kodi-osx-arm64-Omega/tools/depends/target/binary-addons/macosx13.1_arm64-target-release/build/depends/include/libxml2/libxml'
make[7]: *** [libzvbi-prefix/src/libzvbi-stamp/libzvbi-configure] Error 77
make[6]: *** [CMakeFiles/libzvbi.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [build/libzvbi/src/libzvbi-stamp/libzvbi-build] Error 2
make[3]: *** [CMakeFiles/libzvbi.dir/all] Error 2
make[3]: *** Waiting for unfinished jobs....
```

on _ios-aarch64 / tvos-aarch64_ builds there is a different error:
```
clang: error: the clang compiler does not support '-march=all'
make[13]: *** [macosx/sha1-armv8.lo] Error 1
make[13]: *** Waiting for unfinished jobs....
make[12]: *** [all-recursive] Error 1
make[11]: *** [all-recursive] Error 1
make[10]: *** [all] Error 2
make[9]: *** [all-recursive] Error 1
make[8]: *** [all] Error 2
make[7]: *** [gnutls-prefix/src/gnutls-stamp/gnutls-build] Error 2
make[6]: *** [CMakeFiles/gnutls.dir/all] Error 2
make[5]: *** [all] Error 2
make[4]: *** [build/gnutls/src/gnutls-stamp/gnutls-build] Error 2
make[3]: *** [CMakeFiles/gnutls.dir/all] Error 2
make[2]: *** [CMakeFiles/package-inputstream.ffmpegdirect.dir/rule] Error 2
make[1]: *** [package-inputstream.ffmpegdirect] Error 2
```

**Comment by phunkyfish** [comment]
@AlwinEsch any chance you can take a look?

I’m pretty sure when you did the dependencies bump this all worked OK. So I’m not sure what is wrong now.

**Comment by phunkyfish** [comment]
Alwin has the failing builds working now. I’ll get that merged today and then we can bring this in and release it.

**Comment by phunkyfish** [comment]
Other PR merged. Please rebase this PR, all builds should pass then.

**Comment by CastagnaIT** [comment]
done but i think today jenkins is out of service

**Comment by phunkyfish** [comment]
Oh, ok. Then best not to release anything anyway.

**Review by phunkyfish — APPROVED** [review]

**Pull request merged**
