### PR TITLE
add-on dependency updates

### PR DESCRIPTION
**Pull request by AlwinEsch**
This update mostly all dependencies to latest versions, two now includes cmake and no more needs separated between POSIX and Windows.

As following steps comes to change to SSL 3.0.

### CODE REVIEW

**Review by phunkyfish — APPROVED** [review]
Nice work!!!

**Comment by phunkyfish** [comment]
Appears to run well. I’d say just add the version and merge.

**Comment by AlwinEsch** [comment]
> Appears to run well. I’d say just add the version and merge.

Still some depends missing on update. Think the most strange are done and hopefully the others not also produce a fight to become usable on all OS.

**Comment by AlwinEsch** [comment]
The builds on all OS now OK, only needs it runtime tests to confirm correct operation’s.
If someone can look on his OS would be good. Have currently only my Windows laptop available, will try on this, but no good internet in my hotel in England.

**Comment by howie-f** [comment]
deleted: sorry the comment belongs to https://github.com/xbmc/inputstream.ffmpegdirect/pull/247

**Comment by phunkyfish** [comment]
> deleted: sorry the comment belongs to #247

We should likely fix the issue on this PR as the others are already merged. This one needs a rebase anyway.

**Comment by phunkyfish** [comment]
Superseded by https://github.com/xbmc/inputstream.ffmpegdirect/pull/267

**Pull request closed without merging**
