### PR TITLE
Allow ffmpeg header "cenc_decryption_key" for manual drm decryption (FFmpeg 5)

### PR DESCRIPTION
**Pull request by Mio-sha512**
Tested on Kodi 20.0-RC2 (19.90.905)  (x86-64 linux)

Can be tested using public mpd link and key (There are some at https://bitmovin.com/demos/drm)

### CODE REVIEW

**Comment by phunkyfish** [comment]
I will merge the PR for ffmpeg5 shortly. Please rebase once I do.

Your commit looks good btw

**Comment by basilgello** [comment]
@Mio-sha512 Can you please rebase the PR and give meaningful commit message rather than "asd"? Also, you are not the "sonypshomer" on Kodi forums?

**Comment by Mio-sha512** [comment]
Hi,

I've tried to refork (because my repo was a fork of @basilgello's FFmpeg 5 fork) my repo I am unsure of if I need too make a new Pull request 

also, I'm not sonypshomer from the forums

**Comment by Mio-sha512** [comment]
I can see nothing has changed on this pr so I'm closing this and making a new one

**Pull request closed without merging**
