### PR TITLE
Support osx-arm64

### PR DESCRIPTION
**Pull request by phunkyfish**
v20.4.0
- Support osx-arm64, i.e. OSX on Apple Silicon

### CODE REVIEW

**Comment by wsnipex** [comment]
you probably need to disable assembly in gmp for arm64, like https://github.com/xbmc/inputstream.ffmpegdirect/blob/Nexus/depends/common/gmp/CMakeLists.txt#L11-L13

**Comment by wsnipex** [comment]
better yet, gmp 6.2.1 is supposed to support apple silicon: https://gmplib.org/repo/gmp-6.2/rev/7e686e7f836e
we currently use 6.2.0, so a bump might just fix it.

**Comment by phunkyfish** [comment]
Will try bumping the version first.

**Comment by wsnipex** [comment]
I guess you need to set --host=aarch64-apple-darwin" to trigger the correct assembly: https://gmplib.org/repo/gmp-6.2/rev/510b83519d1c

**Pull request merged**
