### PR TITLE
add-on depends library updates

### PR DESCRIPTION
**Pull request by AlwinEsch**
v21.3.5
- Update depednencies to fix building on apple silicon (gnutls 3.8.4) and binutils on linux (2.41 or higher)

To have newest versions on dependencies and to fix problem on https://github.com/xbmc/inputstream.ffmpegdirect/pull/284

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Should now ready for review

**Review by phunkyfish — APPROVED** [review]
Nice, thanks!

**Comment by AlwinEsch** [comment]
Should it be becoming a version increase and release or has you planned additional changes on add-on about?

**Comment by fuzzard** [comment]
Hold off on this. There are serious questions regarding the upstream xz-utils tarballs. See team repo for details

**Comment by fuzzard** [comment]
Drop the xz-utils bump for now thanks.

**Comment by AlwinEsch** [comment]
> Drop the xz-utils bump for now thanks.

Thanks @fuzzard, dropped the xzutils away.

**Comment by phunkyfish** [comment]
Strange, even though we dropped the xz-utils commit builds are still failing on Windows.

```
-- Using src='https://tukaani.org/xz/xz-5.4.3.tar.xz'
-- [download 100% complete]
-- [download 6% complete]
-- [download 11% complete]
-- [download 13% complete]
-- [download 31% complete]
-- [download 41% complete]
-- [download 46% complete]
-- [download 60% complete]
-- [download 83% complete]
-- [download 100% complete]
-- verifying file...
       file='C:/jenkins-workspace/workspace/binary-addons/kodi-windows-i686-Omega/cmake/addons/build/download/xz-5.4.3.tar.xz'
-- SHA256 hash of
    C:/jenkins-workspace/workspace/binary-addons/kodi-windows-i686-Omega/cmake/addons/build/download/xz-5.4.3.tar.xz
  does not match expected value
    expected: '92177bef62c3824b4badc524f8abcce54a20b7dbcfb84cde0a2eb8b49159518c'
      actual: '3881a256b0e563fc18fc1c47d8c533cdb3a311bac2920f726d01cb2449f00c97'
-- Hash mismatch, removing...
```

**Comment by phunkyfish** [comment]
Ah, maybe it's because the repo has been disabled:

Screenshot 2024-03-30 at 09 00 33

So we can't download it the unaffected tarball.

**Comment by AlwinEsch** [comment]
> Strange, even though we dropped the xz-utils commit builds are still failing on Windows.
>> Ah, maybe it's because the repo has been disabled:
>> So we can't download it the unaffected tarball.

No this was already on sunday and monday where I started on DevCon with depends update, the strange was/is, if I build locally it has always worked with sha256, but within CI's it seems to come different one. 

This wrong checksum was always equal. In retrospect, this shasum error makes me very thoughtful, not that something is actually being injected with a modified package using evil proxies.

**Comment by AlwinEsch** [comment]
@phunkyfish have pushed a update to use xz-utils from our mirror, is then 5.4.1 instead of 5.4.3, but as github and his https://tukaani.org/xz no more available should older better.

**Comment by AlwinEsch** [comment]
Thanks a lot @phunkyfish for the update to version 5.4.3 and the release.

**Comment by phunkyfish** [comment]
All the thanks to you @AlwinEsch, I only did the way bits 😉

**Pull request merged**
