### PR TITLE
update msys2 to version 2021-07-25 (to fix some CI)

### PR DESCRIPTION
**Pull request by AlwinEsch**
Hope thats work on our CI's, at home it was OK after change of install values given here https://www.msys2.org/docs/ci/.

About use of our mirror, has set the "if" there to 0, but thing we can also remove as the new have other mirrors and download system as the old and our one have not the newest.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
It seems that thank god the admin OS access, because of SSH or whatever it was, removed again.

**Comment by AlwinEsch** [comment]
Stream test on Windows was OK with it :smile:

**Comment by AlwinEsch** [comment]
Juhu, all builds succesfully done :tada:, maybe your pinned issue then can be closed too, if it no more fails so many times.

**Comment by phunkyfish** [comment]
This is amazing, thanks so much! Making changes has been horrible as we couldn’t use the msys server for downloads.

**Review by phunkyfish — APPROVED** [review]
Thanks for this. We should also upload the same tarball to our mirrors in case we need the fallback tarball at some stage.

**Pull request merged**
