### PR TITLE
Fix ffmpeg configure option for Android

### PR DESCRIPTION
**Pull request by glennguy**
Includes the lib path in linker options.
FFMPEG was being given -liconv during the 'check can compile' part of the configure step, the path where iconv libs are placed was not being included.

### CODE REVIEW

**Comment by glennguy** [comment]
~~Hi @AlwinEsch 
Would you be able to provide some advice? I don't think this is the right solution to the problem but at least shows where the problem is. I think we need to build libiconv as well - no idea why this wasn't an issue before though???~~
@phunkyfish does this look ok?

**Comment by phunkyfish** [comment]
> ~Hi @AlwinEsch Would you be able to provide some advice? I don't think this is the right solution to the problem but at least shows where the problem is. I think we need to build libiconv as well - no idea why this wasn't an issue before though???~
> @phunkyfish does this look ok?

It makes sense. Let’s see if it builds.

**Comment by glennguy** [comment]
Looks good from what I can see, builds fine locally as well.

**Comment by phunkyfish** [comment]
> Looks good from what I can see, builds fine locally as well.



> Looks good from what I can see, builds fine locally as well.

Ah, it’s just the azure builds are broken. Jenkins is good.

**Review by phunkyfish — APPROVED** [review]
Just add the usual version increment and changelog entry and this can be merged and released.

**Comment by phunkyfish** [comment]
The commit name should be changed as well. To `Fix configure option for android`

**Comment by phunkyfish** [comment]
Ok cool. I can force push to your branch. So I fixed the commit message and I'll merge this and fix the Azure builds while I'm at it.

**Pull request merged**
