### PR TITLE
Update to FFmpeg 6.0 including OpenSSL versions for Windows builds

### PR DESCRIPTION
**Pull request by AlwinEsch**
Related to Windows build errors with FFMpeg 6.0 (https://github.com/xbmc/inputstream.ffmpegdirect/pull/235)

@phunkyfish have temporary your commits inside to see it works now.

### CODE REVIEW

**Comment by AlwinEsch** [comment]
Note about the ARM64-UWP error, there it seems to need an gas-preprocessor update, see https://github.com/FFmpeg/gas-preprocessor/commit/09c2c13bd695e6c80fae8480698f0437e6a3f760

Why I not thought earlier about :cry:.

**Comment by phunkyfish** [comment]
Let’s use your PR for this as it’s good.

**Comment by phunkyfish** [comment]
And thanks for all the effort on this. Great to see this going green 😃

**Comment by AlwinEsch** [comment]
Yes, hard work to become green :smile:, will look now about the OpenSSL version 3 on another request.
Only strange that newest OpenSSL 1.1.1t fails.

**Comment by phunkyfish** [comment]
> Yes, hard work to become green 😄, will look now about the OpenSSL version 3 on another request.
> Only strange that newest OpenSSL 1.1.1t fails.

My hope is that with OpenSSL 3 the cross platform mess goes away and we get simpler builds for the likes of windows. It would be nice to have one version of SSL that we could use anywhere.

**Pull request merged**
