### PR TITLE
Allow ffmpeg header "cenc_decryption_key"

### PR DESCRIPTION
**Pull request by Mio-sha512**
Tested on Kodi 20.0-RC2 (19.90.905) (x86-64 linux) also tested on Android (armv7)

Can be tested using public mpd link's and key (There are some at https://bitmovin.com/demos/drm)

Hope this fixes the problem haha

### CODE REVIEW

**Comment by phunkyfish** [comment]
You can drop the other commits now as they are already in this branch. You only need your `cenc_decryption_key` commit now.

**Comment by Mio-sha512** [comment]
I'm gonna just redo my pr because my whole fork seems to be out-dated at this point

**Comment by lrusak** [comment]
> I'm gonna just redo my pr because my whole fork seems to be out-dated at this point

You can just rebase and force push.

**Comment by Pellizca2** [comment]
Hello, @Mio-sha512 how to use?¿ Putting this #KODIPROP:inputstream.ffmpegdirect.cenc_decryption_key= ??

**Comment by Mio-sha512** [comment]
Hi @Pellizca2
It works like this:
```#KODIPROP:inputstream=inputstream.ffmpegdirect
#KODIPROP:mimetype=application/dash+xml
#KODIPROP:inputstream.ffmpegdirect.manifest_type=mpd
#EXTINF: -1 tvg-id="somechannel.tv" tvg-name="SomeChannel", SomeChannel
https://somewebsite.com/manifest.mpd|cenc_decryption_key=KEY

**Comment by Pellizca2** [comment]
Thank you @Mio-sha512

**Comment by Pellizca2** [comment]
It is working on Android Kodi 21. But it is not working on Corelec 21 (kodi 21 also). @Mio-sha512 @phunkyfish

**Comment by phunkyfish** [comment]
This would need to be raised with the coreelec team.

**Comment by Pellizca2** [comment]
Thank you. @Portisch can you merge that into Coreelec?

**Comment by phunkyfish** [comment]
Specifically this is the required commit

https://github.com/xbmc/inputstream.ffmpegdirect/commit/8abecab5fbfcce64a2a82a11738bfaa3de35653d

Bit as it committed on the Omega branch it really should be in CoreElec already.

**Pull request closed without merging**
